### ISSUE TITLE
输入命令报错

### ISSUE THREAD

**Issue by 1529960009** [pcrbot/sys_stats_HoshinoBot#1]
![QQ截图20220326224303](https://user-images.githubusercontent.com/45947734/160244568-4fbc202b-825f-427c-aa36-d763381d5716.png)

**Comment by SlightDust** [comment]
草，我拿在win服务器试了一下也这样了

**Comment by SlightDust** [comment]
你的D盘是不是也显示是一个光驱？
![image](https://user-images.githubusercontent.com/53001305/160250807-60f736c8-8e9f-43a0-a8cf-35e686c68179.png)

**Comment by SlightDust** [comment]
试试最新代码
